const productos = [
    {id: 1,nombre: "El Gran Libro de Programacion en C", precio: 15990, imagen: "https://http2.mlstatic.com/D_NQ_NP_657496-MLC85252612083_052025-O.webp", descripcion: "Con este libro, aprenderás desde los conceptos básicos hasta técnicas avanzadas de programación en C. Ideal para principiantes y programadores experimentados que desean perfeccionar sus habilidades.", categoria: "libro", oferta: true, descuento: 20},
    {id: 2,nombre: "Programacion para Principiantes", precio: 5990, imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY8AN9iPuA3zUu2HPWjyDqn6nvfTvfbWaYXA&s", descripcion: "Programacion para principiantes es una guia completa para aquellos que desean iniciarse en el mundo de la programacion. Con ejemplos claros y ejercicios practicos, este libro te llevara paso a paso desde los conceptos basicos hasta la creacion de tus propios proyectos, ayudandote a entender la logica de la programacion.", categoria: "libro", oferta: false, descuento: 0},
    {id: 3,nombre: "Python de principio a fin", precio: 9990, imagen: "https://m.media-amazon.com/images/S/aplus-media/kdp/347158d0-07a2-4fe8-a122-ba05f819dda5.__CR0,3,220,220_PT0_SX220_V1___.jpg", descripcion: "Python de principio a fin es un libro diseñado para llevarte desde los conceptos basicos hasta las aplicaciones avanzadas del lenguaje de programacion Python. Con explicaciones claras, ejemplos practicos y proyectos interesantes, este libro es ideal tanto para principiantes como para programadores experimentados que desean profundizar en Python.", categoria: "libro", oferta: true, descuento: 10},
    {id: 4,nombre: "JavaScript: The Good Parts", precio: 17990, imagen: "https://www.oreilly.co.jp/books/images/picture_large978-4-87311-391-3.jpeg", descripcion: "JavaScript: The Good Parts es un libro que se enfoca en las mejores caracteristicas del lenguaje de programacion JavaScript. Escrita por Douglas Crockford, esta obra destaca las partes mas efectivas y eficientes de JavaScript, ayudando a los desarrolladores a escribir codigo mas limpio y mantenible.", categoria: "libro", oferta: false, descuento: 0},
    {id: 5,nombre: "Codigo Limpio (Clean Code)", precio: 14990, imagen: "https://images.cdn1.buscalibre.com/fit-in/360x360/87/da/87da3d378f0336fd04014c4ea153d064.jpg", descripcion: "Codigo Limpio (Clean Code) es un libro esencial para desarrolladores de software que buscan mejorar la calidad de su codigo. Escrito por Robert C. Martin, este libro ofrece principios y mejores practicas para escribir codigo claro, legible y mantenible, ayudando a los programadores a crear software de alta calidad.", categoria: "libro", oferta: false, descuento: 0},
    {id: 6,nombre: "Design Patterns", precio: 25590, imagen: "https://m.media-amazon.com/images/S/aplus-media-library-service-media/f9e255ba-6512-410c-b6c7-f545d8a65992.__CR197,0,1105,1383_PT0_SX362_V1___.jpg", descripcion: "Design Patterns Elements of Reusable object-oriented Software es un libro fundamental que introduce patrones de diseno para el desarrollo de software orientado a objetos. Escrito por Erich Gamma, Richard Helm, Ralph Johnson y John Vlissides, este libro proporciona soluciones probadas a problemas comunes de diseno, ayudando a los desarrolladores a crear sistemas mas flexibles y reutilizables.", categoria: "libro", oferta: true, descuento: 15},
    {id: 7,nombre: "El Programador Programatico", precio: 27990, imagen: "https://images.cdn2.buscalibre.com/fit-in/360x360/03/1a/031af9d7e401bb2d08911c317ecbedad.jpg", descripcion: "El Programador Programatico es un libro que explora las mejores practicas y principios para convertirse en un programador eficiente y efectivo. A traves de consejos practicos y ejemplos reales, este libro ayuda a los desarrolladores a mejorar sus habilidades tecnicas y a adoptar una mentalidad de programacion profesional.", categoria: "libro", oferta: false, descuento: 0},
    {id: 8,nombre: "Patrones de diseño Head First", precio: 19990, imagen: "https://images.cdn1.buscalibre.com/fit-in/360x360/47/51/475128f55891670c8706fa9daa0e71e1.jpg", descripcion: " Patrones de diseño Head First es un libro que presenta los patrones de diseno de software de una manera visual y facil de entender. Utilizando un enfoque interactivo y ejemplos practicos, este libro ayuda a los desarrolladores a comprender y aplicar patrones de diseno para crear software mas eficiente y mantenible.", categoria: "libro", oferta: false, descuento: 0},
    {id: 9,nombre: "Introducción a los algoritmos, 3ra Edicion", precio: 16990, imagen: "https://cdn-prod.hanbit.co.kr/books/B8210609999_l.jpg", descripcion: "Introducción a los algoritmos, 3ra Edicion es un libro completo que cubre una amplia gama de algoritmos y estructuras de datos. Escrito por Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest y Clifford Stein, este libro es ideal tanto para estudiantes como para profesionales que desean profundizar en el estudio de los algoritmos y su aplicacion en la programacion.", categoria: "libro", oferta: false, descuento: 0},
    {id: 10,nombre: "Ciencia de datos: Conocimientos Esenciales", precio: 25990, imagen: "https://storage-aws-production.publica.la/tienda-ediciones-uc/issues/2024/12/BgMfnHLqjVT2jK1E/76e90ef8-7a05-42e8-a4e5-325932bb8bb5_cover.jpg", descripcion: "Ciencia de datos: Conocimientos Esenciales es un libro que proporciona una introduccion completa a los conceptos y tecnicas fundamentales de la ciencia de datos. A traves de ejemplos practicos y estudios de caso, este libro ayuda a los lectores a comprender como analizar, interpretar y visualizar datos para tomar decisiones informadas.", categoria: "libro", oferta: false, descuento: 0},
    {id: 11,nombre: "Deep Learning", precio: 25990, imagen: "https://mit-press-new-us.imgix.net/covers/9780262537551.jpg?auto=format&w=298", descripcion: "Deep Learning es un libro que explora los conceptos y tecnicas fundamentales del aprendizaje profundo, una rama avanzada de la inteligencia artificial. Escrito por John D. Kelleher, Yoshua Bengio y Aaron Courville, este libro proporciona una introduccion completa a las redes neuronales y sus aplicaciones en areas como el reconocimiento de imagenes, el procesamiento del lenguaje natural y la robótica.", categoria: "libro", oferta: false, descuento: 0},
    {id: 12,nombre: "Machine Learning", precio: 25990, imagen: "https://machinelearningbook.com/wp-content/uploads/2020/11/FMLPDA_2ed_Cover.jpg", descripcion: "Machine Learning es un libro que ofrece una introduccion completa a los conceptos y tecnicas del aprendizaje automatico. Escrito por John D. Kelleher, este libro cubre una amplia gama de temas, desde algoritmos basicos hasta tecnicas avanzadas, ayudando a los lectores a comprender como construir sistemas que pueden aprender y mejorar a partir de los datos.", categoria: "libro", oferta: false, descuento: 0},
    {id: 13,nombre: "Inteligencia Artificial: Un Enfoque Moderno 1ra Edicion", precio: 29990, imagen: "https://image.cdn0.buscalibre.com/513e35e3f2af8cf12ba3e844.RS500x500.jpg", descripcion: "Inteligencia Artificial: Un Enfoque Moderno 1ra Edicion es un libro que proporciona una introduccion completa a los conceptos y tecnicas de la inteligencia artificial. Escrito por Stuart Russell y Peter Norvig, este libro cubre una amplia gama de temas, desde algoritmos de busqueda hasta aprendizaje automatico, ayudando a los lectores a comprender como construir sistemas inteligentes.", categoria: "libro", oferta: false, descuento: 0},
    {id: 14,nombre: "Inteligencia Artificial: Un Enfoque Moderno 2da Edicion", precio: 29990, imagen: "https://pictures.abebooks.com/isbn/9788420540030-es.jpg", descripcion: "Inteligencia Artificial: Un Enfoque Moderno 2da Edicion es un libro que proporciona una introduccion completa a los conceptos y tecnicas de la inteligencia artificial. Escrito por Stuart Russell y Peter Norvig, este libro cubre una amplia gama de temas, desde algoritmos de busqueda hasta aprendizaje automatico, ayudando a los lectores a comprender como construir sistemas inteligentes.", categoria: "libro", oferta: false, descuento: 0},
    {id: 15,nombre: "Curso basico de Programacion Web", precio: 30000, imagen: "https://blinktech.com.ng/wp-content/uploads/2024/06/I-Will-Write-Javascript-Html-Css-Php-Jquery-Code-For-You.jpeg", descripcion: "En este curso basico de programacion web, aprenderas los fundamentos del desarrollo web, incluyendo HTML, CSS y JavaScript. A traves de lecciones practicas y proyectos interactivos, este curso te proporcionara las habilidades necesarias para crear sitios web atractivos y funcionales desde cero.", categoria: "Curso", oferta: false, descuento: 0},
    {id: 16,nombre: "Curso de Machine Learning", precio: 30000, imagen: "/6-blogs/assets/curso.jpg", descripcion: "El 18 de septiembre se estrenara un nuevo curso para la plataforma , en esta oportunidad te entregamos todo el conocimiento sobre el Machine Learning y la IA", categoria: "Curso", oferta: false, descuento: 0}
  ];
export default productos;